services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:1337"
    volumes:
      - .:/app
    ports:
      - "1337:1337"
    environment:
      - DEBUG=1
