# Generated by Django 4.2 on 2024-08-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_participant_id_alter_participant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Email'),
        ),
    ]
